# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

frobenius_norm <- function(mat1, mat2) {
    .Call('GERGM_frobenius_norm', PACKAGE = 'GERGM', mat1, mat2)
}

Metropolis_Hastings_Sampler <- function(number_of_iterations, shape_parameter, number_of_nodes, statistics_to_use, initial_network, take_sample_every, thetas, triples, pairs, alphas, together, seed, number_of_samples_to_store, using_correlation_network, undirect_network) {
    .Call('GERGM_Metropolis_Hastings_Sampler', PACKAGE = 'GERGM', number_of_iterations, shape_parameter, number_of_nodes, statistics_to_use, initial_network, take_sample_every, thetas, triples, pairs, alphas, together, seed, number_of_samples_to_store, using_correlation_network, undirect_network)
}

weighted_mple_objective <- function(number_of_nodes, statistics_to_use, current_network, thetas, triples, pairs, alphas, together, integration_interval) {
    .Call('GERGM_weighted_mple_objective', PACKAGE = 'GERGM', number_of_nodes, statistics_to_use, current_network, thetas, triples, pairs, alphas, together, integration_interval)
}

